IQSS/dataverse-kubernetes

README.md, dataverse-k8s/bin/config-job.sh, k8s/utils/configure-job.yaml
=> 16 - Add database configuration scripting

README.md, dataverse-k8s/Dockerfile, k8s/bootstrap.yaml, k8s/dataverse.yaml, k8s/solr.yaml, k8s/utils/configure-job.yaml, solr-k8s/Dockerfile
=> 18 Provide 4.12 images

dataverse-k8s/bin/init_1_conf_glassfish.sh, k8s/dataverse.yaml
=> 25 - Mount DOI secret in Pod container

README.md
=> 28 - add docs on s3 secret

README.md, k8s/dataverse/jobs/inplace-reindex.yaml
=> 18 - add a batch job triggering an inplace reindex.

k8s/dataverse/configmap.yaml
=> 39 - remove empty data tag violating K8s schema spec

README.md, docker/dataverse-k8s/Dockerfile, docker/solr-k8s/Dockerfile, k8s/dataverse/deployment.yaml, k8s/dataverse/jobs/bootstrap.yaml, k8s/dataverse/jobs/configure.yaml, k8s/solr/deployment.yaml
=> 48 update v4.14

README.md, docs/k3s-demo/demo-secrets.yaml, docs/k3s-demo/kustomization.yaml, docs/k3s-demo/patch-pvc-k3s.yaml, docs/k3s.md, k8s/dataverse/kustomization.yaml, k8s/solr/kustomization.yaml, k8s/utils/postgresql/kustomization.yaml, test/lint.sh
=> 26 - document usage with k3s

README.md, docs/config.md, docs/how-it-works.md, docs/images.md, docs/little-helpers.md, docs/reuse.md, docs/secrets.md
=> WIP: 44 More and refactor documentation

README.md
As discussed at http://irclog.iq.harvard.edu/dataverse/2019-05-20
=> clarify that dataverse-kubernetes is community supported

docs/minikube.md
=> 57 - Minikube infos on RAM and PV

docs/k3s.md, docs/minikube.md
=> 60 - notes about upstream regression

README.md, docker/dataverse-k8s/Dockerfile, docker/solr-k8s/Dockerfile, docs/images.md, k8s/dataverse/deployment.yaml, k8s/dataverse/jobs/bootstrap.yaml, k8s/dataverse/jobs/configure.yaml, k8s/solr/deployment.yaml
Solves #67. 
Tested new deployment on local minikube cluster, no problems during login, dataverse creation, dataset creation, file upload.
=> 67 - update to v4.15

docs/how-it-works.md
=> 52 - enhancing UML diagram of inner workings

test/lint.sh
=> Update to kubeval 0.10.0

docs/config.md, docs/little-helpers.md, k8s/dataverse/configmap.yaml, k8s/dataverse/deployment.yaml, k8s/dataverse/jobs/bootstrap.yaml, k8s/dataverse/jobs/configure.yaml, k8s/dataverse/jobs/inplace-reindex.yaml, k8s/dataverse/pvc.yaml, k8s/dataverse/svc.yaml, k8s/solr/deployment.yaml, k8s/solr/pvc.yaml, k8s/solr/svc.yaml, k8s/utils/demo-secrets.yaml, k8s/utils/mailcatcher.yaml, k8s/utils/postgresql/deployment.yaml, k8s/utils/postgresql/pvc.yaml, k8s/utils/postgresql/svc.yaml
Fixes #55.
I followed https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels for what labels to add. Should be sufficient to select resources.
=> 55 - Fix metadata for Kubernetes objects

docs/config.md
=> Corrected configure Job path and name.

README.md, docker/dataverse-k8s/bin/bootstrap-job.sh, docker/dataverse-k8s/bin/config-job.sh, docker/dataverse-k8s/bin/metadata-update.sh, docker/dataverse-k8s/glassfish/Dockerfile, docker/dataverse-k8s/glassfish/bin/default.config, docs/metadata.md, k8s/dataverse/deployment.yaml, k8s/dataverse/jobs/bootstrap.yaml, k8s/dataverse/jobs/configure.yaml, k8s/dataverse/jobs/inplace-reindex.yaml, k8s/dataverse/jobs/metadata-update.yaml, k8s/dataverse/svc.yaml
=> 83 - metadata jobs

README.md, docker/dataverse-k8s/bin/bootstrap-job.sh, docker/dataverse-k8s/glassfish/bin/default.config, docs/release-notes/4.16-75-admin-password.md, docs/secrets.md, k8s/dataverse/jobs/bootstrap.yaml, k8s/utils/demo-secrets.yaml
=> 75 password provisioning

docs/metadata.md, k8s/dataverse/deployment.yaml, k8s/dataverse/jobs/bootstrap.yaml, k8s/dataverse/jobs/configure.yaml, k8s/dataverse/jobs/inplace-reindex.yaml, k8s/dataverse/jobs/metadata-reexport.yaml, k8s/dataverse/jobs/metadata-update.yaml, k8s/solr/deployment.yaml
Relates to #83, adding the necessary metadata re-export job.
=> 83 - reexport job

README.md, docker/dataverse-k8s/glassfish/Dockerfile, docker/solr-k8s/Dockerfile, docs/images.md, docs/release-notes/4.16-upgrade.md, k8s/dataverse/deployment.yaml, k8s/solr/deployment.yaml, kustomization.yaml, prepare-release.sh
=> 83 upgrade v4.16

README.md, docker/dataverse-k8s/glassfish/Dockerfile, docs/how-it-works.md, docs/release-notes/4.16-65-docroot.md, docs/storage.md, k8s/dataverse/deployment.yaml, k8s/dataverse/pvc.yaml
=> 65 docroot

k8s/dataverse/kustomization.yaml, k8s/solr/deployment.yaml, k8s/solr/kustomization.yaml, kustomization.yaml
Solves first half of #86 by defining proper K8s probes for the pod. Prometheus is still a second thing.
=> 86 - solr probes (but no prometheus)

docker/dataverse-k8s/Jenkinsfile, docker/solr-k8s/Jenkinsfile
=> 122 jenkins tag fix

docker/dataverse-k8s/Jenkinsfile, docker/dataverse-k8s/glassfish/Dockerfile, docker/dataverse-k8s/glassfish/bin/default.config, docker/dataverse-k8s/glassfish/bin/init_1_conf_glassfish.sh, docker/solr-k8s/Jenkinsfile, docs/day1/architecture.rst, docs/day1/index.rst, docs/day1/resources.rst, k8s/dataverse/deployment.yaml, k8s/solr/deployment.yaml, personas/demo/kustomization.yaml, personas/demo/patch-memory.yaml
Closes #21 
Closes #111
Closes #128
Closes #136
Relates to #131
=> Fix (smaller) multiple issues at once

docker/dataverse-k8s/Jenkinsfile, docker/solr-k8s/Jenkinsfile, docs/images/push-description.sh
Closes #104
Currently, I cannot push the description from Jenkins.
Using the script locally works.
This might be a problem of rate limiting, thus wait before we merge and re-test.
=> 104 dockerhub description

docker/dataverse-k8s/Jenkinsfile, docker/dataverse-k8s/build-cache/Dockerfile, docker/dataverse-k8s/build-cache/Jenkinsfile, docker/dataverse-k8s/glassfish-dev/Dockerfile, docs/images/dataverse-k8s.md
=> 141 buildcache

README.rst, docs/conf.py, docs/images/build.rst, docs/images/dataverse-k8s.md, docs/images/solr-k8s.md, k8s/dataverse/deployment.yaml, k8s/dataverse/kustomization.yaml, k8s/kustomization.yaml, k8s/solr/deployment.yaml, k8s/solr/kustomization.yaml, prepare-release.sh
=> 133 upgrade 4.17

README.rst, docker/dataverse-k8s/glassfish/Dockerfile, docker/solr-k8s/Dockerfile, docs/conf.py, docs/images/build.rst, docs/images/dataverse-k8s.md, docs/images/solr-k8s.md, k8s/dataverse/deployment.yaml, k8s/dataverse/kustomization.yaml, k8s/kustomization.yaml, k8s/solr/deployment.yaml, k8s/solr/kustomization.yaml
=> Upgrade to v4.18.1 with images, docs and submodule ref

k8s/dataverse/pvc.yaml, k8s/solr/pvc.yaml, personas/demo-aws/patch-pvc-aws.yaml, personas/demo-k3s/patch-pvc-k3s.yaml, personas/demo/postgresql/pvc.yaml
=> 153 - removing selectors from PVCs 

docs/day1/scripts/decrypt.py, docs/day1/secrets.rst
=> 157 - Extend docs about tools to handle secrets

docker/dataverse-k8s/bin/bootstrap-job.sh, docs/day1/config.rst, docs/day1/job-bootstrap.rst, personas/demo/configmap.yaml, personas/demo/kustomization.yaml
=> 163 bootstrap configure

docs/Dockerfile, docs/Jenkinsfile, docs/requirements.txt
=> 155 - repair Jenkins sphinx docs build

docker/solr-k8s/Dockerfile
Closes #161 
See also IQSS/dataverse#6599, IQSS/dataverse#6633 and IQSS/dataverse#6631
=> 161 - update to Solr 7.7.2

docker/dataverse-k8s/glassfish/Dockerfile, k8s/dataverse/deployment.yaml
Closes #177 
Relates to #178 and IQSS/dataverse#6656
=> 177 - Workaround for PrimeFaces uploads via Web UI

docker/solr-k8s/schema/init.sh
=> 188 - Fix Solr init container
